version: '3'

services:
   ftpproxy:
        build: ./src
        image: shogoki/delegate-ftp-proxy:latest
        networks:
                 - ftp
        
        ports:
                 - "21:21"
                 - "30000-30009:30000-30009"

        restart: always

networks:
   ftp:
        external:
                 name: ftpproxy
